services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - sportcenter_network

  backend:
    image: enkas1/devops2_backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - sportcenter_network
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Mydatabase1391
      - DATABASE_NAME=postgres
    volumes:
      - shared-volume:/app/templates  # Använd den delade volymen

  frontend:
    image: enkas1/devops2_frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - sportcenter_network
    depends_on:
      - backend
    volumes:
      - shared-volume:/usr/share/nginx/html/templates  # Använd den delade volymen
    

networks:
  sportcenter_network:
    name: sportcenter_network
    driver: bridge

volumes:
  db_data:
  shared-volume:
